version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: analytics_postgres
    environment:
      POSTGRES_DB: analytics_db
      POSTGRES_USER: analytics_user
      POSTGRES_PASSWORD: analytics_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U analytics_user -d analytics_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: analytics_app
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://analytics_user:analytics_password@postgres:5432/analytics_db?sslmode=disable
      PORT: 8080
      ENVIRONMENT: production
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
